/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ringSigVerifierSol from "./ringSigVerifier.sol";
export type { ringSigVerifierSol };
import type * as secp256K1Sol from "./secp256k1.sol";
export type { secp256K1Sol };
