/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as consumerSol from "./consumer.sol";
export type { consumerSol };
import type * as ringSigVerifierSol from "./ringSigVerifier.sol";
export type { ringSigVerifierSol };
import type * as sbtSol from "./sbt.sol";
export type { sbtSol };
