/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RingSigVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "computeC" | "verifyRingSignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeC",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRingSignature",
    values: [string, BigNumberish[], BigNumberish[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "computeC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyRingSignature",
    data: BytesLike
  ): Result;
}

export interface RingSigVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): RingSigVerifier;
  waitForDeployment(): Promise<this>;

  interface: RingSigVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeC: TypedContractMethod<
    [
      strRing: string,
      message: string,
      r: BigNumberish,
      previousC: BigNumberish,
      previousPubKey: [BigNumberish, BigNumberish]
    ],
    [bigint],
    "view"
  >;

  verifyRingSignature: TypedContractMethod<
    [
      message: string,
      ring: BigNumberish[],
      responses: BigNumberish[],
      c: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeC"
  ): TypedContractMethod<
    [
      strRing: string,
      message: string,
      r: BigNumberish,
      previousC: BigNumberish,
      previousPubKey: [BigNumberish, BigNumberish]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyRingSignature"
  ): TypedContractMethod<
    [
      message: string,
      ring: BigNumberish[],
      responses: BigNumberish[],
      c: BigNumberish
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
